#!/bin/bash -xe

# This script is called by Jenkins to generate release notes.

# The resulting notes must be written to $WORKSPACE/artifacts/release_notes

export PREVIOUS_TAG=${RE_HOOK_PREVIOUS_VERSION}
export NEW_TAG=${RE_HOOK_VERSION}
export REPO_URL=${RE_HOOK_REPO_HTTP_URL}

apt-get install -y pandoc

pip install osa_differ==0.3.10 rpc_differ==0.3.12 reno==2.11.2
pip3 install 'rpc_component==0.0.2'

gating/generate_release_notes/generate_release_notes.sh

cp all_notes.md "${RE_HOOK_RELEASE_NOTES}"
