#!/bin/bash -xe

# This script is called by Jenkins to generate release notes.

# The resulting notes must be written to $WORKSPACE/artifacts/release_notes

export PREVIOUS_TAG=${RE_HOOK_PREVIOUS_VERSION}
export NEW_TAG=${RE_HOOK_VERSION}
export REPO_URL=${RE_HOOK_REPO_HTTP_URL}

apt-get install -y pandoc python3-dev python-dev

pip install dulwich -c upper-constraints.txt
pip install -r test-requirements.txt -c upper-constraints.txt
pip3 install 'rpc_component==0.0.2'

gating/generate_release_notes/generate_release_notes.sh

cp all_notes.md "${RE_HOOK_RELEASE_NOTES}"
