---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This playbook's function is to update the git clones for all
# git repositories use by the OpenStack-Ansible integrated build.
#
# The playbook intentionally clones the full repository to ensure
# that it's usable by all RPC releases, regardless of branch.
#
# The playbook also intentionally uses the OSA master branch as it
# is expected to contain more repositories than RPC will need, but
# will always have a complete set.

- name: Push the updated clones to rpc-repo
  hosts: mirrors
  vars:
    repo_local_path: "/openstack/{{ repo_container_name }}/repo"
    repo_remote_path: "/var/www/repo"
  tasks:

    - name: Ensure that target directories exist
      file:
        path: "{{ repo_remote_path }}/{{ item }}"
        state: directory
        owner: "nginx"
        group: "www-data"
      with_items:
        - "pools"
        - "links"
        - "venvs/{{ rpc_release }}/{{ repo_release_name }}"
        - "os-releases/{{ rpc_release }}/{{ repo_release_name }}"

    - name: Push new pools data
      synchronize:
        src: "{{ repo_local_path }}/pools/"
        dest: "{{ repo_remote_path }}/pools"
        mode: push
        delete: no
        recursive: yes
        rsync_opts:
          - "--chown=nginx:www-data"
      register: synchronize
      until: synchronize | success
      retries: 5
      delay: 5

    - name: Push new links data
      synchronize:
        src: "{{ repo_local_path }}/links/"
        dest: "{{ repo_remote_path }}/links"
        mode: push
        delete: no
        recursive: yes
        rsync_opts:
          - "--chown=nginx:www-data"
          - "--exclude index.html"
      register: synchronize
      until: synchronize | success
      retries: 5
      delay: 5

    - name: Push new venvs data
      synchronize:
        src: "{{ repo_local_path }}/venvs/{{ rpc_release }}/{{ repo_release_name }}"
        dest: "{{ repo_remote_path }}/venvs/{{ rpc_release }}/"
        mode: push
        delete: yes
        recursive: yes
        rsync_opts:
          - "--chown=nginx:www-data"
      register: synchronize
      until: synchronize | success
      retries: 5
      delay: 5

    - name: Push new os-releases data
      synchronize:
        src: "{{ repo_local_path }}/os-releases/{{ rpc_release }}/{{ repo_release_name }}"
        dest: "{{ repo_remote_path }}/os-releases/{{ rpc_release }}/"
        mode: push
        delete: yes
        recursive: yes
        rsync_opts:
          - "--chown=nginx:www-data"
      register: synchronize
      until: synchronize | success
      retries: 5
      delay: 5
