#!/bin/bash

## Shell Opts ----------------------------------------------------------------

set -eux
set -o pipefail

## Vars ----------------------------------------------------------------------

## Main ----------------------------------------------------------------------

# We need to ensure that we use the rackspace mirrors, as they are
# most reliable. We also need to ensure that python and the python
# yaml library are present for ansible to work.
source "$(readlink -f $(dirname ${0}))/../gating_prerequisites.sh"
