#!/bin/bash

## Shell Opts ----------------------------------------------------------------

set -e -u -x
set -o pipefail

## Main ----------------------------------------------------------------------

if [ $RE_JOB_ACTION != "tox-test" ]; then
  bash -c "$(readlink -f $(dirname ${0})/post_deploy.sh)"
fi
