#!/bin/bash

## Shell Opts ----------------------------------------------------------------

set -eux
set -o pipefail

## Vars ----------------------------------------------------------------------

## Main ----------------------------------------------------------------------

# If the current folder's basename is rpc-openstack then we assume
# that it is the root of the git clone. If the git clone is not in
# /opt then we symlink the current folder there so that all the
# rpc-openstack scripts work as expected.
if [[ "$(basename ${PWD})" == "rpc-openstack" ]]; then
  if [[ "${PWD}" != "/opt/rpc-openstack" ]]; then
    ln -sfn ${PWD} /opt/rpc-openstack
  fi
fi
