#!/bin/bash

## Shell Opts ----------------------------------------------------------------

set -euv
set -o pipefail

## Display environment
echo "+-------------------- ENV VARS --------------------+"
env
echo "+-------------------- ENV VARS --------------------+"

## Main ----------------------------------------------------------------------

if [ $RE_JOB_ACTION == "tox-test" ]; then
  bash -c "$(readlink -f $(dirname ${0})/run_tox.sh)"
else
  bash -c "$(readlink -f $(dirname ${0})/run_deploy.sh)"
fi
