---
# Copyright 2016, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Setup hosts for rpc-pre-upgrades
  hosts: localhost
  user: root
  roles:
    - { role: "rpc_pre_upgrade", tags: [ "rpc-pre-upgrades" ] }

- name: remove beaver
  hosts: all
  user: root
  tags:
    - rpc-pre-upgrades
    - remove-beaver
  tasks:
    - name: Check if beaver is installed
      stat:
        path: /etc/init.d/beaver
      register: beaver_init_script
      changed_when: false

    - name: Make sure beaver is stopped
      service:
        name: beaver
        enabled: no
        state: stopped
      when: beaver_init_script.stat.exists

    - name: Remove beaver etc files
      file:
        path: /etc/beaver
        state: absent

    - name: Remove beaver init files
      file:
        path: /etc/init.d/beaver
        state: absent

    - name: Remove beaver logrotate files
      file:
        path: /etc/logrotate.d/beaver
        state: absent

    - name: Remove beaver log files
      file:
        path: /var/log/beaver
        state: absent

    - name: Check if beaver is installed
      shell: pip show -q Beaver
      register: is_beaver_installed
      failed_when: false
      changed_when: false

    - name: Uninstall beaver pip package
      pip:
        name: beaver
        state: absent
      when: is_beaver_installed.rc == 0

    - name: Remove beaver user
      user:
        name: beaver
        state: absent

    - name: Remove beaver group
      group:
        name: beaver
        state: absent
