#!/bin/bash

## Shell Opts ----------------------------------------------------------------

set -eux
set -o pipefail

## Main ----------------------------------------------------------------------

if [ $RE_JOB_ACTION != "tox-test" ]; then
  bash -c "$(readlink -f $(dirname ${0})/post_deploy.sh)"
fi

if [ $RE_JOB_ACTION == "system" ]; then
  bash -c "$(readlink -f $(dirname ${0})/post_send_junit_to_qtest.sh)"
fi
