#!/bin/bash

## Shell Opts ----------------------------------------------------------------

set -eux
set -o pipefail

## Vars ----------------------------------------------------------------------

source "$(readlink -f $(dirname ${0}))/../gating_vars.sh"

## Main ----------------------------------------------------------------------

# If the current folder's basename is rpc-openstack then we assume
# that it is the root of the git clone. If the git clone is not in
# /opt then we symlink the current folder there so that all the
# rpc-openstack scripts work as expected.
if [[ "$(basename ${PWD})" == "rpc-openstack" ]]; then
  if [[ "${PWD}" != "/opt/rpc-openstack" ]]; then
    ln -sfn ${PWD} /opt/rpc-openstack
  fi
fi

# We need to ensure that we use the rackspace mirrors, as they are
# most reliable. We also need to ensure that python and the python
# yaml library are present for ansible to work.
source "$(readlink -f $(dirname ${0}))/../gating_prerequisites.sh"

# Install pre-requisites for the different types of tests
distro_pkgs_to_install=""
py_pkgs_to_install=""

if [[ $RE_JOB_ACTION == "tox-test" ]]; then
  dpkg-query --list | grep wget &>/dev/null || distro_pkgs_to_install+="wget "
  pip freeze | grep tox &>/dev/null || py_pkgs_to_install+="tox==3.3.0 "
fi

if [ "${distro_pkgs_to_install}" != "" ]; then
  apt-get install -y ${distro_pkgs_to_install}
fi

if [ "${py_pkgs_to_install}" != "" ]; then
  pip install --disable-pip-version-check --upgrade --upgrade-strategy only-if-needed ${py_pkgs_to_install}
fi

