#!/bin/bash

## Shell Opts ----------------------------------------------------------------

set -e -u -x
set -o pipefail

## Display environment
echo "+-------------------- ENV VARS --------------------+"
env
echo "+-------------------- ENV VARS --------------------+"

## Vars ----------------------------------------------------------------------

export DEPLOY_AIO="true"
export MNAIO_VAR_FILE="${MNAIO_VAR_FILE:-/tmp/mnaio_vars}"
# These vars are set by the CI environment, but are given defaults
# here to cater for situations where someone is executing the test
# outside of the CI environment.
export RE_JOB_NAME="${RE_JOB_NAME:-}"
export RE_JOB_IMAGE="${RE_JOB_IMAGE:-}"
export RE_JOB_SCENARIO="${RE_JOB_SCENARIO:-swift}"
export RE_JOB_ACTION="${RE_JOB_ACTION:-deploy}"
export RE_JOB_FLAVOR="${RE_JOB_FLAVOR:-}"
export RE_JOB_TRIGGER="${RE_JOB_TRIGGER:-USER}"
export RE_HOOK_ARTIFACT_DIR="${RE_HOOK_ARTIFACT_DIR:-/tmp/artifacts}"
export RE_HOOK_RESULT_DIR="${RE_HOOK_RESULT_DIR:-/tmp/results}"

## Main ----------------------------------------------------------------------

echo "rpc-openstack at SHA $(git rev-parse HEAD)"

if [[ $RE_JOB_ACTION == "tox-test" ]]; then
  bash -c "$(readlink -f $(dirname ${0})/run_tox.sh)"
elif [[ $RE_JOB_IMAGE =~ .*mnaio.* ]]; then
  bash -c "$(readlink -f $(dirname ${0})/run_deploy_mnaio.sh)"
  source "${MNAIO_VAR_FILE}"
else
  bash -c "$(readlink -f $(dirname ${0})/run_deploy.sh)"
fi

if [[ $RE_JOB_ACTION == system* ]]; then
  bash -c "$(readlink -f $(dirname ${0})/run_system_tests.sh)"
fi
